#! /bin/sh

## GUI

# Cursor
xsetroot -cursor_name left_ptr &
# Key repeat rate
xset r rate 200 30
# Background
nitrogen --restore &

## Essential
pgrep -x sxhkd      > /dev/null || sxhkd &
pgrep -x bspswallow > /dev/null || ~/.config/bspwm/bspswallow/bspswallow &

## Misc
~/.config/dunst/startdunst
~/.config/picom/startpicom
~/.config/polybar/startpolybar

## Apps

# Name 'telegram-desktop' is too long for pgrep so it cuts to 'telegram-deskto'
# pgrep -x telegram-deskto     > /dev/null || telegram-desktop -startintray &
pgrep -x fcitx5              > /dev/null || fcitx5 -d &

# Settings
bspc monitor DP-2   -d 1 2 3 4
bspc monitor HDMI-0 -d 5 6 7 8

bspc config border_width        0
bspc config window_gap          5

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

